

<center>
    <img src="https://miro.medium.com/v2/resize:fit:300/1*mgncZaKaVx9U6OCQu_m8Bg.jpeg">
</center>



The goal of PCA is to extract information while reducing the number of features
from a dataset by identifying which existing features relate to another. The crux of the algorithm is trying to determine the relationship between existing features, called principal components, and then quantifying how relevant these principal components are. The principal components are used to transform the high dimensional data to a lower dimensional data while preserving as much information. For a principal component to be relevant, it needs to capture information about the features. We can determine the relationships between features using covariance.

In [1]:
#import necessary package
import numpy as np

In [2]:

data = np.array([
    [   1,   2,  -1,   4,  10],
    [   3,  -3,  -3,  12, -15],
    [   2,   1,  -2,   4,   5],
    [   5,   1,  -5,  10,   5],
    [   2,   3,  -3,   5,  12],
    [   4,   0,  -3,  16,   2],
])

### Step 1: Standardize the Data along the Features

![image.png](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxe5VYCBsaZddkkTZlCY24Yov4JJD4-ArTA&usqp=CAU)




Explain why we need to handle the data on the same scale.

**[TO DO: Insert Answer here]**

***Why we need to hand the data on the same scale***

- The reason why we standardize or normalize data is :
            
            - Avoid bias in algorithms; it prevents features with larger scales from dominating the learning process and biases the model

            - Improves convergence; it helps optimization algorithms like gradient descent to converge faster and more reliably

            - Interpretability and Comparability; standardized data makes it easier to interpret feature importance and compare their effects

            - Regularization and Stability; standardization stabilizes regularization techniques and prevents features from disproportionaely affecting regulation

In [3]:
# Calculate the mean
mean = np.mean(data, axis=0)

# Calculate the standard deviation
std_dv = np.std(data, axis=0)

# Standardize the data
standardized_data = (data - mean) / std_dv

print(standardized_data)

[[-1.36438208  0.70710678  1.5109662  -0.99186978  0.77802924]
 [ 0.12403473 -1.94454365 -0.13736056  0.77145428 -2.06841919]
 [-0.62017367  0.1767767   0.68680282 -0.99186978  0.20873955]
 [ 1.61245155  0.1767767  -1.78568733  0.33062326  0.20873955]
 [-0.62017367  1.23743687 -0.13736056 -0.77145428  1.00574511]
 [ 0.86824314 -0.35355339 -0.13736056  1.65311631 -0.13283426]]


![cov matrix.webp](https://dmitry.ai/uploads/default/original/1X/9bd2851674ebb55e404cc3ff5e2ffe65b42ff460.png)

We use the pair - wise covariance of the different features to determine how they relate to each other. With these covariances, our goal is to group / cluster based on similar patterns. Intuitively, we can relate features if they have similar covariances with other features.

### Step 2: Calculate the Covariance Matrix



In [4]:
# use `ddof = 1` if using sample data (default assumption) and use `ddof = 0` if using population data

cov_matrix = np.cov(standardized_data, ddof=1, rowvar=False)


print(f"\nCovariance Matrix: \n{cov_matrix}")


Covariance Matrix: 
[[ 1.2        -0.42098785 -1.0835838   0.90219291 -0.37000528]
 [-0.42098785  1.2         0.20397003 -0.77149364  1.18751836]
 [-1.0835838   0.20397003  1.2        -0.59947269  0.22208218]
 [ 0.90219291 -0.77149364 -0.59947269  1.2        -0.70017993]
 [-0.37000528  1.18751836  0.22208218 -0.70017993  1.2       ]]


### Step 3: Eigendecomposition on the Covariance Matrix


In [5]:


eigenvalues, eigenvectors = np.linalg.eig(cov_matrix) #TO DO: Insert code here for eigenvalues, eigenvectors

print(f"\nEigenvalues: \n{eigenvalues}")
print(f"\nEigenvectors: \n{eigenvectors}")


Eigenvalues: 
[3.80985761e+00 1.73655615e+00 4.94531029e-02 4.74189469e-05
 4.04085720e-01]

Eigenvectors: 
[[-0.4640131   0.45182808 -0.70733581  0.28128049 -0.03317471]
 [ 0.45019005  0.48800851  0.29051532  0.6706731  -0.15803498]
 [ 0.37929082 -0.55665017 -0.48462321  0.24186072 -0.5029143 ]
 [-0.4976889   0.03162214  0.36999674 -0.03373724 -0.78311558]
 [ 0.43642295  0.49682965 -0.20861365 -0.64143906 -0.32822489]]


### Step 4: Sort the Principal Components

In [6]:
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

order_of_importance = np.argsort(eigenvalues)[::-1]
print ( 'the order of importance is :\n {}'.format(order_of_importance))

# utilize the sort order to sort eigenvalues and eigenvectors
sorted_eigenvalues = eigenvalues[order_of_importance]

print('\n\n sorted eigen values:\n{}'.format(sorted_eigenvalues))
sorted_eigenvectors = eigenvectors[:, order_of_importance] # sort the columns
print('\n\n The sorted eigen vector matrix is: \n {}'.format(sorted_eigenvectors))

the order of importance is :
 [0 1 4 2 3]


 sorted eigen values:
[3.80985761e+00 1.73655615e+00 4.04085720e-01 4.94531029e-02
 4.74189469e-05]


 The sorted eigen vector matrix is: 
 [[-0.4640131   0.45182808 -0.03317471 -0.70733581  0.28128049]
 [ 0.45019005  0.48800851 -0.15803498  0.29051532  0.6706731 ]
 [ 0.37929082 -0.55665017 -0.5029143  -0.48462321  0.24186072]
 [-0.4976889   0.03162214 -0.78311558  0.36999674 -0.03373724]
 [ 0.43642295  0.49682965 -0.32822489 -0.20861365 -0.64143906]]


Question:

1. Why do we order eigen values and eigen vectors?

[We order eigenvalues and eigenvectors to identify the most significant principal components ]

2. Is it true we would consider the lowest eigen value compared to the highest? Defend your answer

[No, we prioritize the highest eigenvalues as they represent the principal components capturing the most variance, essential for preserving information in techniques like PCS]


You want to see what percentage of information each eigen value holds. You would have print out the percentage of each eigen value using the formula



> (sorted eigen values / sum of all sorted eigen values) * 100



In [7]:
# use sorted_eigenvalues to ensure the explained variances correspond to the eigenvectors

#TO DO: Insert code here
explained_variance = (sorted_eigenvalues / np.sum(sorted_eigenvalues)) * 100
explained_variance =["{:.2f}%".format(value) for value in explained_variance]
print( explained_variance)

['63.50%', '28.94%', '6.73%', '0.82%', '0.00%']


#Initialize the number of Principle components then perfrom matrix multiplication with the variable K example k = 3 for 3 priciple components




> The reulting matrix (with reduced data) = standardized data * vector with columns k

See expected output for k = 2



In [8]:
k = 2

reduced_data = np.matmul(standardized_data, sorted_eigenvectors[:,:k])

In [9]:
print(reduced_data)

[[ 2.3577116  -0.75728867]
 [-2.27171739 -1.81970663]
 [ 1.21259114 -0.50390931]
 [-1.41935914  1.9229856 ]
 [ 1.61562536  0.87541857]
 [-1.49485157  0.28250044]]


In [10]:
print(reduced_data.shape)

(6, 2)


# *What are 2 positive effects and 2 negative effects of PCA

Give 2 Benefits and 2 limitations
[
    **Benefits (Positive Effects):**

1. Dimensionality Reduction: PCA helps in reducing the dimensionality of data by transforming it into a lower-dimensional space while retaining most of the variance. This reduction can lead to faster computation times and reduced storage requirements.
2. Feature Combination: PCA can combine correlated features into fewer uncorrelated components (principal components). This feature combination can help in simplifying the dataset and improving model performance by reducing multicollinearity.

**Limitations (Negative Effects):**

1. Loss of Interpretability: After applying PCA, the new components (principal components) might not have direct physical or intuitive meaning like the original features. This loss of interpretability can make it challenging to explain the underlying factors driving the data.
2. Information Loss: PCA aims to capture the maximum variance in the data, but this can lead to information loss, especially if the lower-dimensional representation does not retain enough information to fully represent the original dataset. It's important to balance dimensionality reduction with retaining sufficient information for meaningful analysis.]